checks:
    python:
        code_rating: true
        duplicate_code: true
filter:
    excluded_paths:
        - 'tests/*' 
build:
    environment:
        python: '3.6.0'
    tests:
        before:
            - 'pip3 install pylint Coverage'
        override:
            -
                command: 'coverage run --include="*diff_register*" setup.py test'
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
                idle_timeout: 720
	    -
                command: 'pylint diff_register --output-format=parseable --reports=n --include-naming-hint=y | tee pylint-data'
                analysis:
                    file: 'pylint-data'
                    format: 'pylint-parseable'
